[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

# Esta es la forma correcta para aplicar el tiempo a las Server Actions de Next.js
[functions."*"]
  timeout = 26
